import localFont from "next/font/local";
import "./globals.css";
import "./embla.css";
import Navbar from "@/components/navbar/navbar";
import { Poppins } from "next/font/google";
import GlobalBackground from "@/components/backgound";
import Footer from "@/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased relative`}>
        {/* <GlobalBackground /> */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
