export const surveyData = {
  finance: {
    title: "Finance Health Checkup",
    description: "Deep dive into governance and technology readiness.",
    dimensions: ["Control & Governance", "Visibility", "Process", "Technology", "People", "Strategy"],
    questions: [
      // Section 1: Control & Governance
      { id: 1, dimension: "Control & Governance", question: "No single person owns banking, data entry and reporting end to end.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 2, dimension: "Control & Governance", question: "Approval matrices exist in writing and are actually followed, not just on paper.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 3, dimension: "Control & Governance", question: "Every material transaction leaves a clear and traceable audit trail.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 4, dimension: "Control & Governance", question: "Compliance — tax, regulatory, statutory — is always current with no last-minute surprises.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 5, dimension: "Control & Governance", question: "If my finance lead left tomorrow, the function would still run for 30 days without me stepping in.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },

      // Section 2: Visibility
      { id: 6, dimension: "Visibility", question: "Monthly MIS is ready and in my hands on or before the 10th of the following month.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 7, dimension: "Visibility", question: "I can see cash position, receivables and payables in one consolidated view at any time.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 8, dimension: "Visibility", question: "Revenue and margin are broken down by product, customer or geography, not just in aggregate.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 9, dimension: "Visibility", question: "We have a rolling cash flow forecast that we actively monitor and trust.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 10, dimension: "Visibility", question: "Our financial data is reliable enough to make a major strategic decision on it today.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },

      // Section 3: Process
      { id: 11, dimension: "Process", question: "Month-end close follows a documented, repeatable checklist, every single month.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 12, dimension: "Process", question: "Reconciliations happen on a fixed schedule, not on demand when something looks off.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 13, dimension: "Process", question: "Vendor onboarding, invoicing and collections follow a standardised, documented process.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 14, dimension: "Process", question: "Budgeting and forecasting runs on a defined cycle, not just when someone asks for it.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 15, dimension: "Process", question: "Variance analysis is performed regularly and actually influences the plan for the next period.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },

      // Section 4: Technology
      { id: 16, dimension: "Technology", question: "Core systems, accounting, billing, payroll and banking, are integrated and talk to each other.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 17, dimension: "Technology", question: "Less than 20% of finance team time is spent on manual data entry or repetitive tasks.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 18, dimension: "Technology", question: "I have a live dashboard I can open right now that shows the numbers that actually matter.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 19, dimension: "Technology", question: "Reconciliations are automated, not a weekly spreadsheet exercise.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 20, dimension: "Technology", question: "Our ERP or accounting software is being used to its full capability, not just as a ledger.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },

      // Section 5: People
      { id: 21, dimension: "People", question: "My finance team sends insights and analysis, not just numbers and transaction reports.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 22, dimension: "People", question: "Every finance role has a written description with clear accountability for outcomes.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 23, dimension: "People", question: "There is a trained backup for every critical finance role in the team.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 24, dimension: "People", question: "Performance is reviewed against outcomes and measurable improvements, not just hours logged.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 25, dimension: "People", question: "We invest in upskilling the finance team regularly, not only when something breaks.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },

      // Section 6: Strategy
      { id: 26, dimension: "Strategy", question: "Finance is actively in the room when we make decisions on pricing, hiring or expansion.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 27, dimension: "Strategy", question: "We use financial modelling and forward-looking data to plan for growth, not just explain the past..", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 28, dimension: "Strategy", question: "Working capital — receivables, payables, inventory — is actively managed as a strategic lever.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 29, dimension: "Strategy", question: "We evaluate profitability at a granular level: by product, customer, unit or channel.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 30, dimension: "Strategy", question: "Finance is aligned with and actively contributes to the long-term business strategy.", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
    ]
  },
  payally: {
    title: "Pay-Ally P2P Survey",
    description: "Evaluate procurement lifecycle and payment efficiency.",
    dimensions: ["Automation", "Visibility", "Compliance", "Vendor Management", "Cost Efficiency", "Data Integrity"],
    questions: [
      { id: 1, dimension: "Automation", question: "Are your purchase requisitions and approvals handled through an automated digital workflow?", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 2, dimension: "Automation", question: "Is your P2P process seamlessly integrated with your ERP/Accounting system without manual data entry?", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 3, dimension: "Visibility", question: "Do you have a real-time dashboard for all outstanding liabilities and upcoming vendor payments?", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 4, dimension: "Visibility", question: "Can you track the status of a specific invoice from receipt to payment in seconds?", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 5, dimension: "Compliance", question: "Are all payments matched against purchase orders and receipts (3-way match) automatically?", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 6, dimension: "Compliance", question: "Do you have an automated audit trail for every procurement transaction and approval?", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 7, dimension: "Vendor Management", question: "Do you have a centralized portal for vendor onboarding and direct communication?", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 8, dimension: "Vendor Management", question: "Is your vendor master data regularly audited and updated for compliance and risk?", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 9, dimension: "Cost Efficiency", question: "Are you consistently capturing early payment discounts from your vendors?", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 10, dimension: "Cost Efficiency", question: "Can your procurement process handle a 50% increase in volume without adding headcount?", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 11, dimension: "Data Integrity", question: "Are you free from duplicate payments or data entry errors in your accounts payable?", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
      { id: 12, dimension: "Data Integrity", question: "Can you generate an accurate vendor spend analysis report in less than 5 minutes?", options: [{ text: "Strongly Disagree", score: 1 }, { text: "Disagree", score: 2 }, { text: "Neutral", score: 3 }, { text: "Agree", score: 4 }, { text: "Strongly Agree", score: 5 }] },
    ]
  }
};
